language: node_js 
node_js:
  14
os:
  - linux

script:
  - node build.js
  - zip -r abtipa.zip public/
  - mv abtipa.zip public/abtipa.zip

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  skip_cleanup: true
  on:
    branch: master
