language: node_js 
os:
  - linux

script:
  - node build.js
  - zip -r abtipa.zip public/
  - mv abtipa.zip public/abtipa.zip

deploy:
  provider: public
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: book
  skip_cleanup: true
  on:
    branch: master
